name: Update data
on:
  workflow_dispatch:
  schedule:
    - cron:  '15 0 * * *'
jobs:
  scrape:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          wget -O data-full.json https://lz4.overpass-api.de/api/interpreter\?data\=%0A%09%09%09%5Bout%3Ajson%5D%5Btimeout%3A200%5D%3B%0A%09%09%09%2F%2F%20gather%20results%0A%09%09%09\(%0A%09%09%09%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9C%22seamark%3Alight%3Asequence%22%3D\*%E2%80%9D%0A%09%09%09%20%20node%5B%22seamark%3Alight%3Asequence%22%5D\(-90%2C-180%2C90%2C180\)%3B%0A%09%09%09%20%20way%5B%22seamark%3Alight%3Asequence%22%5D\(-90%2C-180%2C90%2C180\)%3B%0A%09%09%09\)%3B%0A%09%09%09%2F%2F%20print%20results%0A%09%09%09out%20body%3B%0A%09%09%09%3E%3B%0A%09%09%09out%20skel%20qt%3B%0A%09%09
      - name: Commit the data
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 10
          max_attempts: 5
          command: |
            git config --global user.name 'Pierre Mesure (Github Actions)'
            git config --global user.email 'pierre@mesu.re'
            git add data-full.json
            git commit -am "Updating the data"
            git push
